name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          jvm_distribution: 'adopt'
          jvm_version: '17'
