name: Build Debug

on:
  push:
    branches: [ main ]
    paths:
      - '**.kt'
      - '**.kts'
      - 'gradle.properties'
      - 'gradle-wrapper.properties'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.kt'
      - '**.kts'
      - 'gradle.properties'
      - 'gradle-wrapper.properties'
      - '.github/workflows/build.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  verify:
    name: "Check"
    runs-on: ubuntu-latest
    env:
      JVM_DISTRIBUTION: 'adopt'
      JVM_VERSION: '11'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3

      - name: Check
        run: ./gradlew check

  build-android:
    name: Build Android APKs
    runs-on: ubuntu-latest
    env:
      JVM_DISTRIBUTION: 'adopt'
      JVM_VERSION: '17'
    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Build project
        run: ./gradlew assembleDebug

      - uses: kittaakos/upload-artifact-as-is@v0
        with:
          path: |
            android/**/build/outputs/apk/debug/*-debug.apk
