name: Build Debug

on:
  push:
    branches: [ main ]
    paths:
      - '**.kt'
      - '**.kts'
      - 'gradle.properties'
      - 'gradle-wrapper.properties'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.kt'
      - '**.kts'
      - 'gradle.properties'
      - 'gradle-wrapper.properties'
      - '.github/workflows/build.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  verify:
    name: "Check"
    runs-on: ubuntu-latest
    env:
      JVM_DISTRIBUTION: 'adopt'
      JVM_VERSION: '11'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3

      - name: Check
        run: ./gradlew check
  
  build-android:
    name: Build Android APKs
    runs-on: ubuntu-latest
    env:
      JVM_DISTRIBUTION: 'adopt'
      JVM_VERSION: '11'
    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Build project
        run: ./gradlew assembleDebug

      - uses: kittaakos/upload-artifact-as-is@v0
        with:
          path: |
            android/**/build/outputs/apk/debug/*-debug.apk

  build-desktop:
    name: Build Desktop executables
    strategy:
      matrix:
        runtime: [ linux-x64, win-x64 ]
        include:
          - runtime: linux-x64
            arch: x64
            os: ubuntu-latest
            shell: bash
            build: packageReleaseUberJarForCurrentOS packageDeb

          - runtime: win-x64
            arch: x64
            os: windows-latest
            shell: powershell
            build: packageReleaseUberJarForCurrentOS packageExe

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    defaults:
      run:
        shell: ${{ matrix.shell }}
    env:
      JVM_DISTRIBUTION: 'adopt'
      JVM_VERSION: '11'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JVM_DISTRIBUTION }}
          java-version: ${{ env.JVM_VERSION }}
          architecture: ${{ matrix.arch }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: ./gradlew ${{ matrix.build }}

      # Upload runner package tar.gz/zip as artifact
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: desktop-${{ matrix.runtime }}
          path: |
            desktop/build/compose/binaries/main/*/
            desktop/build/compose/binaries/main-release/*/
            desktop/build/compose/jars/
            !desktop/build/compose/binaries/main/app/

      # Upload runner errors
      - name: Upload error logs
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: runner-errors-${{ matrix.runtime }}
          path: |
            desktop/build/compose/logs/
